# Generated by Django 6.0.1 on 2026-04-20 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
    ]
