# Generated by Django 6.0.1 on 2026-04-20 00:22

import os
from django.contrib.auth import get_user_model
from django.db import migrations

def create_superuser(apps, schema_editor):
    User = get_user_model()
    username = os.environ.get('DJANGO_SUPERUSER_USERNAME')
    email = os.environ.get('DJANGO_SUPERUSER_EMAIL')
    password = os.environ.get('DJANGO_SUPERUSER_PASSWORD')

    if username and password:
        if not User.objects.filter(username=username).exists():
            User.objects.create_superuser(
                username=username,
                email=email,
                password=password
            )

class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20260420_0021'),
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]
